import pytest
from httpx import ASGITransport, AsyncClient

from app.agents.campaign_agent import CampaignAgent
from app.api.dependencies import get_campaign_agent, get_campaign_image_service, get_sheets_service
from app.config import Settings
from app.main import app
from app.models.campaign import Campaign
from app.models.campaign_content import (
    CampaignContentQueueConflictResponse,
    CampaignContentQueueItem,
    CampaignContentQueueSaveResponse,
    CampaignDraftSet,
)
from app.services.campaign_image_service import CampaignImageMetadata
from app.services.llm_service import LLMService


@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"


@pytest.fixture(autouse=True)
def use_placeholder_campaign_agent() -> None:
    async def override_campaign_agent() -> CampaignAgent:
        return CampaignAgent(llm_service=LLMService(app_settings=Settings(llm_provider="placeholder")))

    app.dependency_overrides[get_campaign_agent] = override_campaign_agent
    yield
    app.dependency_overrides.pop(get_campaign_agent, None)


def _campaign(campaign_id: str = "CAMP-1001") -> Campaign:
    return Campaign(
        campaign_id=campaign_id,
        campaign_name="Spring Interior Leads",
        service_focus="Interior painting",
        target_location="Oak Park",
        target_customer="homeowners",
        offer="Free quote request",
        cta="Request a quote",
        landing_page_url="https://gomezpainting.example/quote",
        start_date="2026-05-01",
        end_date="2026-05-31",
        status="Active",
        notes="Focus on living rooms and bedrooms.",
    )


def _existing_campaign_queue_items(campaign_id: str = "CAMP-1001") -> list[CampaignContentQueueItem]:
    return [
        CampaignContentQueueItem(
            content_id=f"CCQ-existing-{platform.lower().replace(' ', '-')}",
            campaign_id=campaign_id,
            platform=platform,
            draft_text=f"Existing {platform} draft.",
            cta="Request a quote",
            landing_page_url="https://gomezpainting.example/quote",
            created_at="2026-04-28T00:00:00Z",
            notes="Generated by CampaignAgent",
        )
        for platform in ["Facebook", "Google Business", "Instagram", "Craigslist", "Nextdoor"]
    ]


class FakeCampaignSheetsService:
    def __init__(
        self,
        campaigns: list[Campaign],
        existing_queue_items: list[CampaignContentQueueItem] | None = None,
    ) -> None:
        self.campaigns = campaigns
        self.existing_queue_items = existing_queue_items or []
        self.saved_queue_items: list[CampaignContentQueueItem] = []
        self.append_count = 0

    def list_campaigns(self) -> list[Campaign]:
        return self.campaigns

    def get_campaign_by_id(self, campaign_id: str) -> Campaign | None:
        for campaign in self.campaigns:
            if campaign.campaign_id == campaign_id:
                return campaign
        return None

    def get_campaign_content_queue_items_by_campaign_id(self, campaign_id: str) -> list[CampaignContentQueueItem]:
        return [item for item in self.existing_queue_items if item.campaign_id == campaign_id]

    def save_campaign_draft_set_to_queue(
        self,
        campaign: Campaign,
        draft_set: CampaignDraftSet,
        image_metadata: CampaignImageMetadata | None = None,
    ) -> list[CampaignContentQueueItem]:
        self.append_count += 5
        self.saved_queue_items = [
            CampaignContentQueueItem(
                content_id=f"CCQ-test-{platform.lower().replace(' ', '-')}",
                campaign_id=campaign.campaign_id,
                platform=platform,
                draft_text=draft_text,
                cta=campaign.cta,
                landing_page_url=campaign.landing_page_url,
                image_filename=image_metadata.image_filename if image_metadata else None,
                image_path=image_metadata.image_path if image_metadata else None,
                created_at="2026-04-28T00:00:00Z",
                notes="Generated by CampaignAgent",
            )
            for platform, draft_text in [
                ("Facebook", draft_set.facebook_post),
                ("Google Business", draft_set.google_business_post),
                ("Instagram", draft_set.instagram_caption),
                ("Craigslist", draft_set.craigslist_post),
                ("Nextdoor", draft_set.nextdoor_post),
            ]
        ]
        return self.saved_queue_items


class FakeCampaignImageService:
    def __init__(self, image_metadata: CampaignImageMetadata | None = None) -> None:
        self.image_metadata = image_metadata
        self.selection_count = 0

    def select_next_image(self) -> CampaignImageMetadata | None:
        self.selection_count += 1
        return self.image_metadata


@pytest.mark.anyio
async def test_list_campaigns_returns_campaigns() -> None:
    async def override_sheets_service() -> FakeCampaignSheetsService:
        return FakeCampaignSheetsService([_campaign()])

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/campaigns")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    data = response.json()
    assert len(data) == 1
    assert Campaign.model_validate(data[0]).campaign_id == "CAMP-1001"


@pytest.mark.anyio
async def test_generate_campaign_content_returns_draft_set() -> None:
    async def override_sheets_service() -> FakeCampaignSheetsService:
        return FakeCampaignSheetsService([_campaign()])

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaigns/CAMP-1001/generate-content")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    draft_set = CampaignDraftSet.model_validate(response.json())
    assert "Oak Park" in draft_set.facebook_post
    assert "https://gomezpainting.example/quote" in draft_set.nextdoor_post
    assert draft_set.needs_human_review is True


@pytest.mark.anyio
async def test_generate_campaign_content_save_returns_draft_and_five_queue_items() -> None:
    fake_sheets_service = FakeCampaignSheetsService([_campaign()])
    fake_image_service = FakeCampaignImageService(
        CampaignImageMetadata(
            image_filename="01-kitchen.webp",
            image_path="/media/campaigns/01-kitchen.webp",
        )
    )

    async def override_sheets_service() -> FakeCampaignSheetsService:
        return fake_sheets_service

    async def override_campaign_image_service() -> FakeCampaignImageService:
        return fake_image_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    app.dependency_overrides[get_campaign_image_service] = override_campaign_image_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaigns/CAMP-1001/generate-content/save")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentQueueSaveResponse.model_validate(response.json())
    assert len(parsed_response.queue_items) == 5
    assert [item.platform for item in parsed_response.queue_items] == [
        "Facebook",
        "Google Business",
        "Instagram",
        "Craigslist",
        "Nextdoor",
    ]
    assert {item.status for item in parsed_response.queue_items} == {"Needs Review"}
    assert {item.approved for item in parsed_response.queue_items} == {"No"}
    assert {item.published for item in parsed_response.queue_items} == {"No"}
    assert {item.image_filename for item in parsed_response.queue_items} == {"01-kitchen.webp"}
    assert {item.image_path for item in parsed_response.queue_items} == {"/media/campaigns/01-kitchen.webp"}
    assert fake_sheets_service.append_count == 5
    assert fake_image_service.selection_count == 1


@pytest.mark.anyio
async def test_generate_campaign_content_save_returns_409_when_drafts_already_exist() -> None:
    fake_sheets_service = FakeCampaignSheetsService(
        [_campaign()],
        existing_queue_items=_existing_campaign_queue_items(),
    )
    fake_image_service = FakeCampaignImageService(
        CampaignImageMetadata(
            image_filename="01-kitchen.webp",
            image_path="/media/campaigns/01-kitchen.webp",
        )
    )

    async def override_sheets_service() -> FakeCampaignSheetsService:
        return fake_sheets_service

    async def override_campaign_image_service() -> FakeCampaignImageService:
        return fake_image_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    app.dependency_overrides[get_campaign_image_service] = override_campaign_image_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaigns/CAMP-1001/generate-content/save")

    app.dependency_overrides.clear()

    assert response.status_code == 409
    parsed_response = CampaignContentQueueConflictResponse.model_validate(response.json())
    assert len(parsed_response.existing_queue_items) == 5
    assert fake_sheets_service.saved_queue_items == []
    assert fake_sheets_service.append_count == 0
    assert fake_image_service.selection_count == 0


@pytest.mark.anyio
async def test_generate_campaign_content_save_force_appends_when_drafts_already_exist() -> None:
    fake_sheets_service = FakeCampaignSheetsService(
        [_campaign()],
        existing_queue_items=_existing_campaign_queue_items(),
    )

    async def override_sheets_service() -> FakeCampaignSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaigns/CAMP-1001/generate-content/save?force=true")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentQueueSaveResponse.model_validate(response.json())
    assert len(parsed_response.queue_items) == 5
    assert fake_sheets_service.append_count == 5


@pytest.mark.anyio
async def test_generate_campaign_content_returns_404_when_campaign_is_missing() -> None:
    async def override_sheets_service() -> FakeCampaignSheetsService:
        return FakeCampaignSheetsService([])

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaigns/CAMP-404/generate-content")

    app.dependency_overrides.clear()

    assert response.status_code == 404
    assert response.json() == {"detail": "Campaign not found for campaign_id: CAMP-404"}
