import pytest
from httpx import ASGITransport, AsyncClient

from app.api.dependencies import get_sheets_service
from app.main import app
from app.models.content_queue import ContentQueueItem


@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"


class FakeContentQueueSheetsService:
    def __init__(self) -> None:
        self.item = ContentQueueItem(
            content_id="CQ-1001-facebook",
            job_id="JOB-1001",
            platform="Facebook",
            draft_text="Facebook draft",
            status="Needs Review",
            approved="No",
            published="No",
            created_at="2026-04-28T00:00:00Z",
            notes="Generated by ContentAgent",
        )
        self.updated_item: ContentQueueItem | None = None

    def list_content_queue_items(self) -> list[ContentQueueItem]:
        return [
            self.item,
            self.item.model_copy(
                update={
                    "content_id": "CQ-1001-instagram",
                    "platform": "Instagram",
                    "draft_text": "Instagram draft",
                }
            ),
        ]

    def approve_content_queue_item(self, content_id: str) -> ContentQueueItem | None:
        return self._update(content_id=content_id, status="Approved", approved="Yes", published="No")

    def reject_content_queue_item(self, content_id: str) -> ContentQueueItem | None:
        return self._update(content_id=content_id, status="Rejected", approved="No", published="No")

    def mark_content_queue_item_published(self, content_id: str) -> ContentQueueItem | None:
        return self._update(content_id=content_id, status="Published", approved="Yes", published="Yes")

    def _update(self, content_id: str, status: str, approved: str, published: str) -> ContentQueueItem | None:
        if content_id != self.item.content_id:
            return None

        self.updated_item = self.item.model_copy(
            update={
                "status": status,
                "approved": approved,
                "published": published,
            }
        )
        return self.updated_item


@pytest.mark.anyio
async def test_list_content_queue_items_returns_queue_items() -> None:
    async def override_sheets_service() -> FakeContentQueueSheetsService:
        return FakeContentQueueSheetsService()

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/content-queue")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    data = response.json()
    assert len(data) == 2
    assert [item["content_id"] for item in data] == ["CQ-1001-facebook", "CQ-1001-instagram"]
    assert [ContentQueueItem.model_validate(item).platform for item in data] == ["Facebook", "Instagram"]


@pytest.mark.anyio
async def test_approve_content_queue_item_returns_updated_item() -> None:
    fake_sheets_service = FakeContentQueueSheetsService()

    async def override_sheets_service() -> FakeContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content-queue/CQ-1001-facebook/approve")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    data = response.json()
    parsed_response = ContentQueueItem.model_validate(data)
    assert parsed_response.status == "Approved"
    assert parsed_response.approved == "Yes"
    assert parsed_response.published == "No"
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_reject_content_queue_item_returns_updated_item() -> None:
    fake_sheets_service = FakeContentQueueSheetsService()

    async def override_sheets_service() -> FakeContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content-queue/CQ-1001-facebook/reject")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = ContentQueueItem.model_validate(response.json())
    assert parsed_response.status == "Rejected"
    assert parsed_response.approved == "No"
    assert parsed_response.published == "No"
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_mark_content_queue_item_published_returns_updated_item() -> None:
    fake_sheets_service = FakeContentQueueSheetsService()

    async def override_sheets_service() -> FakeContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content-queue/CQ-1001-facebook/mark-published")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = ContentQueueItem.model_validate(response.json())
    assert parsed_response.status == "Published"
    assert parsed_response.approved == "Yes"
    assert parsed_response.published == "Yes"
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_content_queue_update_returns_404_when_content_id_is_missing() -> None:
    async def override_sheets_service() -> FakeContentQueueSheetsService:
        return FakeContentQueueSheetsService()

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content-queue/CQ-missing/approve")

    app.dependency_overrides.clear()

    assert response.status_code == 404
    assert response.json() == {"detail": "Content queue item not found for content_id: CQ-missing"}
