import pytest
from httpx import ASGITransport, AsyncClient

from app.api.dependencies import get_publisher_service, get_sheets_service
from app.config import Settings
from app.main import app
from app.models.campaign_content import CampaignContentQueueItem, CampaignContentRunDueResponse
from app.services.publisher_service import PublisherService, PublishingError


@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"


class FakeDueSheetsService:
    def __init__(self) -> None:
        self.item = CampaignContentQueueItem(
            content_id="CCQ-1001-facebook",
            campaign_id="CAMP-1001",
            platform="Facebook",
            draft_text="Facebook campaign draft",
            cta="Request a quote",
            landing_page_url="https://gomezpainting.example/quote",
            status="Approved",
            approved="Yes",
            published="No",
            created_at="2026-04-28T00:00:00Z",
            scheduled_at="2026-04-30T09:00:00Z",
            notes="Generated by CampaignAgent",
        )
        self.updated_item: CampaignContentQueueItem | None = None

    def list_due_campaign_content_queue_items(self) -> list[CampaignContentQueueItem]:
        return [self.item]

    def get_campaign_content_queue_item_by_id(self, content_id: str) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None
        return self.item

    def publish_campaign_content_queue_item(
        self,
        content_id: str,
        published_at: str,
        notes: str,
        external_post_id: str | None = None,
        published_url: str | None = None,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None

        self.updated_item = self.item.model_copy(
            update={
                "status": "Published",
                "published": "Yes",
                "published_at": published_at,
                "publish_attempts": self.item.publish_attempts + 1,
                "last_publish_error": None,
                "external_post_id": external_post_id,
                "published_url": published_url,
                "notes": notes,
            }
        )
        return self.updated_item

    def record_campaign_content_publish_failure(
        self,
        content_id: str,
        error_message: str,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None

        self.updated_item = self.item.model_copy(
            update={
                "publish_attempts": self.item.publish_attempts + 1,
                "last_publish_error": error_message,
                "published": "No",
            }
        )
        return self.updated_item


class FailingPublisherService:
    def publish_campaign_content(self, item: CampaignContentQueueItem):
        raise PublishingError("Mock publish failed.")


@pytest.mark.anyio
async def test_run_due_publishing_publishes_due_items_in_mock_mode() -> None:
    fake_sheets_service = FakeDueSheetsService()
    publisher_service = PublisherService(app_settings=Settings(publisher_mode="mock"))

    async def override_sheets_service() -> FakeDueSheetsService:
        return fake_sheets_service

    async def override_publisher_service() -> PublisherService:
        return publisher_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    app.dependency_overrides[get_publisher_service] = override_publisher_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/publisher/run-due")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentRunDueResponse.model_validate(response.json())
    assert len(parsed_response.published_items) == 1
    assert parsed_response.failed_items == []
    published_item = parsed_response.published_items[0]
    assert published_item.status == "Published"
    assert published_item.published == "Yes"
    assert published_item.publish_attempts == 1
    assert published_item.last_publish_error is None
    assert published_item.external_post_id == "mock-facebook-CCQ-1001-facebook"
    assert published_item.published_url is not None


@pytest.mark.anyio
async def test_run_due_publishing_records_failed_publish_attempt() -> None:
    fake_sheets_service = FakeDueSheetsService()
    failing_publisher_service = FailingPublisherService()

    async def override_sheets_service() -> FakeDueSheetsService:
        return fake_sheets_service

    async def override_publisher_service() -> FailingPublisherService:
        return failing_publisher_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    app.dependency_overrides[get_publisher_service] = override_publisher_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/publisher/run-due")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentRunDueResponse.model_validate(response.json())
    assert parsed_response.published_items == []
    assert len(parsed_response.failed_items) == 1
    failed_item = parsed_response.failed_items[0]
    assert failed_item.published == "No"
    assert failed_item.publish_attempts == 1
    assert failed_item.last_publish_error == "Mock publish failed."
