import pytest
from httpx import ASGITransport, AsyncClient

from app.agents.content_agent import ContentAgent
from app.api.dependencies import get_content_agent, get_sheets_service
from app.config import Settings
from app.main import app
from app.models.completed_job import CompletedJob
from app.models.content_draft import ContentDraft
from app.models.content_queue import ContentQueueConflictResponse, ContentQueueItem, ContentQueueSaveResponse
from app.services.llm_service import LLMService
from app.services.sheets_service import SheetsConfigurationError


@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"


@pytest.fixture(autouse=True)
def use_placeholder_content_agent() -> None:
    async def override_content_agent() -> ContentAgent:
        return ContentAgent(llm_service=LLMService(app_settings=Settings(llm_provider="placeholder")))

    app.dependency_overrides[get_content_agent] = override_content_agent
    yield
    app.dependency_overrides.pop(get_content_agent, None)


class FakeSheetsService:
    def __init__(
        self,
        jobs: list[CompletedJob],
        existing_queue_items: list[ContentQueueItem] | None = None,
    ) -> None:
        self.jobs = jobs
        self.existing_queue_items = existing_queue_items or []
        self.saved_queue_items: list[ContentQueueItem] = []
        self.append_count = 0

    def get_completed_job_by_id(self, job_id: str) -> CompletedJob | None:
        for job in self.jobs:
            if job.job_id == job_id:
                return job
        return None

    def get_content_queue_items_by_job_id(self, job_id: str) -> list[ContentQueueItem]:
        return [item for item in self.existing_queue_items if item.job_id == job_id]

    def save_content_draft_to_queue(self, job_id: str, draft: ContentDraft) -> list[ContentQueueItem]:
        self.append_count += 4
        self.saved_queue_items = [
            ContentQueueItem(
                content_id=f"CQ-test-{platform.lower().replace(' ', '-')}",
                job_id=job_id,
                platform=platform,
                draft_text=draft_text,
                created_at="2026-04-28T00:00:00Z",
                notes="Generated by ContentAgent",
            )
            for platform, draft_text in [
                ("Facebook", draft.facebook_post),
                ("Google Business", draft.google_business_post),
                ("Instagram", draft.instagram_caption),
                ("Review Request", draft.review_request_text),
            ]
        ]
        return self.saved_queue_items


class MissingConfigSheetsService:
    def get_completed_job_by_id(self, job_id: str) -> CompletedJob | None:
        raise SheetsConfigurationError("Google Sheets is not configured.")


def build_existing_queue_items(job_id: str = "JOB-1001") -> list[ContentQueueItem]:
    return [
        ContentQueueItem(
            content_id=f"CQ-existing-{platform.lower().replace(' ', '-')}",
            job_id=job_id,
            platform=platform,
            draft_text=f"Existing {platform} draft.",
            status="Needs Review",
            approved="No",
            published="No",
            created_at="2026-04-28T00:00:00Z",
            notes="Generated by ContentAgent",
        )
        for platform in ["Facebook", "Google Business", "Instagram", "Review Request"]
    ]


@pytest.mark.anyio
async def test_health_check() -> None:
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


@pytest.mark.anyio
async def test_generate_content_returns_structured_draft() -> None:
    payload = {
        "customer": "Maria R.",
        "job_type": "Interior Paint",
        "location": "Oak Park",
        "date_completed": "March 2026",
        "photos_uploaded": True,
        "notes": "Living room repaint with trim refresh.",
    }
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate", json=payload)

    assert response.status_code == 200
    data = response.json()
    assert set(data) == {
        "facebook_post",
        "google_business_post",
        "instagram_caption",
        "review_request_text",
        "confidence",
        "needs_human_review",
    }
    assert "Oak Park" in data["facebook_post"]
    assert "Maria R." in data["review_request_text"]
    assert 0.0 <= data["confidence"] <= 1.0
    assert data["needs_human_review"] is True


@pytest.mark.anyio
async def test_generate_content_from_job_returns_draft_for_matching_sheet_job() -> None:
    job = CompletedJob(
        job_id="JOB-1001",
        customer="Maria R.",
        job_type="Interior Paint",
        location="Oak Park",
        date_completed="March 2026",
        photos_uploaded=True,
        notes="Living room repaint with trim refresh.",
    )

    async def override_sheets_service() -> FakeSheetsService:
        return FakeSheetsService([job])

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate-from-job/JOB-1001")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    data = response.json()
    assert "Oak Park" in data["facebook_post"]
    assert "Maria R." in data["review_request_text"]
    assert data["needs_human_review"] is True


@pytest.mark.anyio
async def test_generate_content_from_job_returns_404_when_job_is_missing() -> None:
    async def override_sheets_service() -> FakeSheetsService:
        return FakeSheetsService([])

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate-from-job/JOB-404")

    app.dependency_overrides.clear()

    assert response.status_code == 404
    assert response.json() == {"detail": "Completed job not found for job_id: JOB-404"}


@pytest.mark.anyio
async def test_generate_content_from_job_save_returns_draft_and_four_queue_items() -> None:
    job = CompletedJob(
        job_id="JOB-1001",
        customer="Maria R.",
        job_type="Interior Paint",
        location="Oak Park",
        date_completed="March 2026",
        photos_uploaded=True,
        notes="Living room repaint with trim refresh.",
    )
    fake_sheets_service = FakeSheetsService([job])

    async def override_sheets_service() -> FakeSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate-from-job/JOB-1001/save")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    data = response.json()
    parsed_response = ContentQueueSaveResponse.model_validate(data)

    assert "content_draft" in data
    assert len(data["queue_items"]) == 4
    assert len(parsed_response.queue_items) == 4
    assert [item["platform"] for item in data["queue_items"]] == [
        "Facebook",
        "Google Business",
        "Instagram",
        "Review Request",
    ]
    assert {item["status"] for item in data["queue_items"]} == {"Needs Review"}
    assert {item["approved"] for item in data["queue_items"]} == {"No"}
    assert {item["published"] for item in data["queue_items"]} == {"No"}
    assert len(fake_sheets_service.saved_queue_items) == 4
    assert fake_sheets_service.append_count == 4


@pytest.mark.anyio
async def test_generate_content_from_job_save_returns_409_when_drafts_already_exist() -> None:
    job = CompletedJob(
        job_id="JOB-1001",
        customer="Maria R.",
        job_type="Interior Paint",
        location="Oak Park",
        date_completed="March 2026",
        photos_uploaded=True,
        notes="Living room repaint with trim refresh.",
    )
    fake_sheets_service = FakeSheetsService([job], existing_queue_items=build_existing_queue_items())

    async def override_sheets_service() -> FakeSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate-from-job/JOB-1001/save")

    app.dependency_overrides.clear()

    assert response.status_code == 409
    data = response.json()
    parsed_response = ContentQueueConflictResponse.model_validate(data)

    assert data["detail"] == (
        "Drafts already exist for this job. Review them in Content Queue instead of generating duplicates."
    )
    assert len(parsed_response.existing_queue_items) == 4
    assert [item["platform"] for item in data["existing_queue_items"]] == [
        "Facebook",
        "Google Business",
        "Instagram",
        "Review Request",
    ]
    assert fake_sheets_service.saved_queue_items == []
    assert fake_sheets_service.append_count == 0


@pytest.mark.anyio
async def test_generate_content_from_job_save_force_appends_when_drafts_already_exist() -> None:
    job = CompletedJob(
        job_id="JOB-1001",
        customer="Maria R.",
        job_type="Interior Paint",
        location="Oak Park",
        date_completed="March 2026",
        photos_uploaded=True,
        notes="Living room repaint with trim refresh.",
    )
    fake_sheets_service = FakeSheetsService([job], existing_queue_items=build_existing_queue_items())

    async def override_sheets_service() -> FakeSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate-from-job/JOB-1001/save?force=true")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    data = response.json()
    parsed_response = ContentQueueSaveResponse.model_validate(data)

    assert len(parsed_response.queue_items) == 4
    assert len(fake_sheets_service.saved_queue_items) == 4
    assert fake_sheets_service.append_count == 4


@pytest.mark.anyio
async def test_generate_content_from_job_save_returns_404_when_job_is_missing() -> None:
    async def override_sheets_service() -> FakeSheetsService:
        return FakeSheetsService([])

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate-from-job/JOB-404/save")

    app.dependency_overrides.clear()

    assert response.status_code == 404
    assert response.json() == {"detail": "Completed job not found for job_id: JOB-404"}


@pytest.mark.anyio
async def test_generate_content_from_job_save_returns_503_when_sheets_config_is_missing() -> None:
    async def override_sheets_service() -> MissingConfigSheetsService:
        return MissingConfigSheetsService()

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/content/generate-from-job/JOB-1001/save")

    app.dependency_overrides.clear()

    assert response.status_code == 503
    assert response.json() == {"detail": "Google Sheets is not configured."}
