from datetime import datetime, timedelta, timezone
from typing import Any
from urllib.parse import parse_qs

import httpx
import pytest

from app.config import Settings
from app.models.campaign_content import CampaignContentQueueItem
from app.services.publisher_service import GoogleBusinessPublisher, PublisherService, PublishingError
from app.services.publishing_workflow_service import PublishingWorkflowService


def google_business_settings() -> Settings:
    return Settings(
        publisher_mode="google_business",
        google_business_client_id="client-id",
        google_business_client_secret="client-secret",
        google_business_refresh_token="refresh-token",
        google_business_account_id="account-123",
        google_business_location_id="location-456",
    )


def meta_settings() -> Settings:
    return Settings(
        publisher_mode="meta",
        meta_graph_api_version="v21.0",
        meta_app_id="app-id",
        meta_app_secret="app-secret",
        facebook_page_id="page-123",
        facebook_page_access_token="page-token",
        instagram_business_account_id="ig-456",
    )


def meta_export_settings() -> Settings:
    return Settings(
        publisher_mode="meta_export",
        meta_graph_api_version="v21.0",
        facebook_page_id="page-123",
        instagram_business_account_id="ig-456",
        api_public_base_url="https://api.example.com",
    )


def queue_item(**overrides: Any) -> CampaignContentQueueItem:
    scheduled_at = (datetime.now(timezone.utc) - timedelta(minutes=5)).isoformat(timespec="seconds").replace(
        "+00:00",
        "Z",
    )
    values: dict[str, Any] = {
        "content_id": "CCQ-1001-google-business",
        "campaign_id": "CAMP-1001",
        "platform": "Google Business",
        "draft_text": "Fresh interior paint completed in Oak Park.",
        "cta": "Request a quote",
        "landing_page_url": "https://gomezpainting.example/quote",
        "image_filename": "room.jpg",
        "image_path": "https://cdn.example.com/room.jpg",
        "status": "Approved",
        "approved": "Yes",
        "published": "No",
        "created_at": "2026-04-28T00:00:00Z",
        "scheduled_at": scheduled_at,
        "notes": "Generated by CampaignAgent",
    }
    values.update(overrides)
    return CampaignContentQueueItem(**values)


class FakeSheetsService:
    def __init__(self, item: CampaignContentQueueItem) -> None:
        self.item = item
        self.updated_item: CampaignContentQueueItem | None = None

    def list_due_campaign_content_queue_items(self) -> list[CampaignContentQueueItem]:
        return [self.item]

    def get_campaign_content_queue_item_by_id(self, content_id: str) -> CampaignContentQueueItem | None:
        return self.item if content_id == self.item.content_id else None

    def publish_campaign_content_queue_item(
        self,
        content_id: str,
        published_at: str,
        notes: str,
        external_post_id: str | None = None,
        published_url: str | None = None,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None
        self.updated_item = self.item.model_copy(
            update={
                "status": "Published",
                "approved": "Yes",
                "published": "Yes",
                "published_at": published_at,
                "publish_attempts": self.item.publish_attempts + 1,
                "last_publish_error": None,
                "external_post_id": external_post_id,
                "published_url": published_url,
                "notes": notes,
            }
        )
        return self.updated_item

    def record_campaign_content_publish_failure(
        self,
        content_id: str,
        error_message: str,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None
        self.updated_item = self.item.model_copy(
            update={
                "publish_attempts": self.item.publish_attempts + 1,
                "last_publish_error": error_message,
                "published": "No",
            }
        )
        return self.updated_item

    def record_campaign_content_publish_result(
        self,
        content_id: str,
        status: str,
        published: str,
        published_at: str | None,
        notes: str,
        external_post_id: str | None = None,
        published_url: str | None = None,
        last_publish_error: str | None = None,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None
        self.updated_item = self.item.model_copy(
            update={
                "status": status,
                "published": published,
                "published_at": published_at,
                "publish_attempts": self.item.publish_attempts + 1,
                "last_publish_error": last_publish_error,
                "external_post_id": external_post_id,
                "published_url": published_url,
                "notes": notes,
            }
        )
        return self.updated_item

    def record_campaign_content_manual_fallback(
        self,
        content_id: str,
        error_message: str,
        copy_ready_package: str,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None
        notes = f"{self.item.notes}\n\n{copy_ready_package}" if self.item.notes else copy_ready_package
        self.updated_item = self.item.model_copy(
            update={
                "status": "Ready for Manual Post",
                "publish_attempts": self.item.publish_attempts + 1,
                "last_publish_error": error_message,
                "published": "No",
                "notes": notes,
            }
        )
        return self.updated_item


def http_client_factory(handler: httpx.MockTransport) -> httpx.Client:
    return httpx.Client(transport=handler)


def form_data(request: httpx.Request) -> dict[str, str]:
    parsed = parse_qs(request.content.decode())
    return {key: values[0] for key, values in parsed.items()}


def test_google_business_maps_queue_item_to_local_post_body() -> None:
    item = queue_item(draft_text=f"{'A' * 1500} extra text", image_url="https://cdn.example.com/preferred.jpg")

    body = GoogleBusinessPublisher.build_local_post_body(item)

    assert body == {
        "languageCode": "en-US",
        "summary": "A" * 1500,
        "topicType": "STANDARD",
        "callToAction": {
            "actionType": "LEARN_MORE",
            "url": "https://gomezpainting.example/quote",
        },
        "media": [
                {
                    "mediaFormat": "PHOTO",
                    "sourceUrl": "https://cdn.example.com/preferred.jpg",
                }
            ],
    }


def test_google_business_missing_credentials_error() -> None:
    publisher = GoogleBusinessPublisher(
        app_settings=Settings(
            publisher_mode="google_business",
            google_business_client_id=None,
            google_business_client_secret=None,
            google_business_refresh_token=None,
            google_business_account_id=None,
            google_business_location_id=None,
        )
    )

    with pytest.raises(PublishingError, match="GOOGLE_BUSINESS_CLIENT_ID"):
        publisher.publish(queue_item())


def test_google_business_success_response_updates_queue_row() -> None:
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if str(request.url) == "https://oauth2.googleapis.com/token":
            return httpx.Response(200, json={"access_token": "access-token"})
        assert (
            str(request.url)
            == "https://mybusiness.googleapis.com/v4/accounts/account-123/locations/location-456/localPosts"
        )
        return httpx.Response(
            200,
            json={
                "name": "accounts/account-123/locations/location-456/localPosts/post-789",
                "searchUrl": "https://g.page/r/post-789",
            },
        )

    sheets_service = FakeSheetsService(queue_item())
    publisher_service = PublisherService(
        app_settings=google_business_settings(),
        google_business_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    workflow = PublishingWorkflowService(sheets_service=sheets_service, publisher_service=publisher_service)

    result = workflow.run_due_publishing()

    assert result.failed_items == []
    assert len(result.published_items) == 1
    published_item = result.published_items[0]
    assert published_item.published == "Yes"
    assert published_item.status == "Published"
    assert published_item.publish_attempts == 1
    assert published_item.last_publish_error is None
    assert published_item.external_post_id == "accounts/account-123/locations/location-456/localPosts/post-789"
    assert published_item.published_url == "https://g.page/r/post-789"
    assert requests[-1].headers["authorization"] == "Bearer access-token"


def test_google_business_verify_uses_newer_account_and_location_apis() -> None:
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if str(request.url) == "https://oauth2.googleapis.com/token":
            return httpx.Response(200, json={"access_token": "access-token"})
        if str(request.url) == "https://mybusinessaccountmanagement.googleapis.com/v1/accounts":
            return httpx.Response(200, json={"accounts": [{"name": "accounts/account-123"}]})
        assert str(request.url).startswith(
            "https://mybusinessbusinessinformation.googleapis.com/v1/accounts/account-123/locations"
        )
        return httpx.Response(200, json={"locations": [{"name": "locations/location-456"}]})

    publisher = GoogleBusinessPublisher(
        app_settings=google_business_settings(),
        http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )

    result = publisher.verify_credentials()

    assert result["ok"] is True
    assert result["account_verification_api"] == "https://mybusinessaccountmanagement.googleapis.com/v1"
    assert result["location_verification_api"] == "https://mybusinessbusinessinformation.googleapis.com/v1"
    assert result["local_posts_publish_api"] == "https://mybusiness.googleapis.com/v4"
    assert [str(request.url).split("?")[0] for request in requests] == [
        "https://oauth2.googleapis.com/token",
        "https://mybusinessaccountmanagement.googleapis.com/v1/accounts",
        "https://mybusinessbusinessinformation.googleapis.com/v1/accounts/account-123/locations",
    ]


def test_google_business_failed_response_saves_last_publish_error() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if str(request.url) == "https://oauth2.googleapis.com/token":
            return httpx.Response(200, json={"access_token": "access-token"})
        return httpx.Response(403, json={"error": {"message": "Location is not authorized."}})

    sheets_service = FakeSheetsService(queue_item())
    publisher_service = PublisherService(
        app_settings=google_business_settings(),
        google_business_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    workflow = PublishingWorkflowService(sheets_service=sheets_service, publisher_service=publisher_service)

    result = workflow.run_due_publishing()

    assert result.published_items == []
    assert len(result.failed_items) == 1
    failed_item = result.failed_items[0]
    assert failed_item.published == "No"
    assert failed_item.publish_attempts == 1
    assert failed_item.last_publish_error is not None
    assert "Location is not authorized." in failed_item.last_publish_error


def test_legacy_local_posts_api_disabled_marks_item_ready_for_manual_post() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if str(request.url) == "https://oauth2.googleapis.com/token":
            return httpx.Response(200, json={"access_token": "access-token"})
        return httpx.Response(
            403,
            json={
                "error": {
                    "code": 403,
                    "message": (
                        "Google My Business API has not been used in project 123 before or it is disabled. "
                        "Enable it by visiting https://console.developers.google.com/apis/api/"
                        "mybusiness.googleapis.com/overview?project=123 then retry."
                    ),
                    "status": "PERMISSION_DENIED",
                    "details": [
                        {
                            "@type": "type.googleapis.com/google.rpc.ErrorInfo",
                            "reason": "SERVICE_DISABLED",
                            "domain": "googleapis.com",
                            "metadata": {"service": "mybusiness.googleapis.com"},
                        }
                    ],
                }
            },
        )

    sheets_service = FakeSheetsService(queue_item())
    publisher_service = PublisherService(
        app_settings=google_business_settings(),
        google_business_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    workflow = PublishingWorkflowService(sheets_service=sheets_service, publisher_service=publisher_service)

    result = workflow.run_due_publishing()

    assert result.published_items == []
    assert len(result.failed_items) == 1
    failed_item = result.failed_items[0]
    assert failed_item.status == "Ready for Manual Post"
    assert failed_item.published == "No"
    assert failed_item.publish_attempts == 1
    assert failed_item.last_publish_error is not None
    assert "legacy Google My Business API" in failed_item.last_publish_error
    assert "Manual Google Business Post Package" in failed_item.notes
    assert "Fresh interior paint completed in Oak Park." in failed_item.notes


def test_unapproved_due_item_is_not_published() -> None:
    class PublisherThatShouldNotRun:
        def __init__(self) -> None:
            self.called = False

        def publish_campaign_content(self, item: CampaignContentQueueItem) -> None:
            self.called = True
            raise AssertionError("Publisher should not be called for unapproved content.")

    publisher_service = PublisherThatShouldNotRun()
    sheets_service = FakeSheetsService(queue_item(status="Needs Review", approved="No"))
    workflow = PublishingWorkflowService(sheets_service=sheets_service, publisher_service=publisher_service)  # type: ignore[arg-type]

    result = workflow.run_due_publishing()

    assert publisher_service.called is False
    assert result.published_items == []
    assert len(result.failed_items) == 1
    assert result.failed_items[0].published == "No"
    assert "must be approved" in (result.failed_items[0].last_publish_error or "")


def test_facebook_page_text_link_payload() -> None:
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        assert str(request.url) == "https://graph.facebook.com/v21.0/page-123/feed"
        data = form_data(request)
        assert data["message"] == "Fresh interior paint completed in Oak Park."
        assert data["link"] == "https://gomezpainting.example/quote"
        assert data["access_token"] == "page-token"
        return httpx.Response(200, json={"id": "page-123_111"})

    sheets_service = FakeSheetsService(queue_item(platform="Facebook Page", image_path=None, image_url=None))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert len(requests) == 1
    assert result.published_items[0].external_post_id == "Facebook=page-123_111"
    assert result.published_items[0].published == "Yes"


def test_facebook_page_image_payload() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert str(request.url) == "https://graph.facebook.com/v21.0/page-123/photos"
        data = form_data(request)
        assert data["url"] == "https://cdn.example.com/room.jpg"
        assert data["caption"] == "Fresh interior paint completed in Oak Park."
        return httpx.Response(200, json={"post_id": "page-123_222"})

    sheets_service = FakeSheetsService(queue_item(platform="Facebook Page"))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert result.published_items[0].external_post_id == "Facebook=page-123_222"


def test_instagram_requires_public_image_url() -> None:
    sheets_service = FakeSheetsService(queue_item(platform="Instagram", image_path="/media/campaigns/room.jpg"))
    publisher_service = PublisherService(app_settings=meta_settings())

    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert result.published_items == []
    failed_item = result.failed_items[0]
    assert failed_item.status == "Publish Blocked"
    assert failed_item.last_publish_error == "Instagram publishing requires a public image URL."


def test_instagram_media_container_publish_flow() -> None:
    requests: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if str(request.url) == "https://graph.facebook.com/v21.0/ig-456/media":
            data = form_data(request)
            assert data["image_url"] == "https://cdn.example.com/room.jpg"
            assert data["caption"] == "Fresh interior paint completed in Oak Park."
            return httpx.Response(200, json={"id": "creation-123"})
        if str(request.url) == "https://graph.facebook.com/v21.0/ig-456/media_publish":
            assert form_data(request)["creation_id"] == "creation-123"
            return httpx.Response(200, json={"id": "ig-media-789"})
        assert str(request.url).startswith("https://graph.facebook.com/v21.0/ig-media-789")
        return httpx.Response(200, json={"id": "ig-media-789", "permalink": "https://instagram.com/p/abc"})

    sheets_service = FakeSheetsService(queue_item(platform="Instagram"))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert [request.method for request in requests] == ["POST", "POST", "GET"]
    assert result.published_items[0].external_post_id == "Instagram=ig-media-789"
    assert result.published_items[0].published_url == "Instagram=https://instagram.com/p/abc"


def test_meta_dual_both_targets_succeed() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        url = str(request.url)
        if url == "https://graph.facebook.com/v21.0/page-123/photos":
            return httpx.Response(200, json={"post_id": "page-123_333"})
        if url == "https://graph.facebook.com/v21.0/ig-456/media":
            return httpx.Response(200, json={"id": "creation-333"})
        if url == "https://graph.facebook.com/v21.0/ig-456/media_publish":
            return httpx.Response(200, json={"id": "ig-media-333"})
        return httpx.Response(200, json={"id": "ig-media-333", "permalink": "https://instagram.com/p/333"})

    sheets_service = FakeSheetsService(queue_item(platform="Meta Dual"))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    published_item = result.published_items[0]
    assert published_item.status == "Published"
    assert published_item.published == "Yes"
    assert "Facebook=page-123_333" in (published_item.external_post_id or "")
    assert "Instagram=ig-media-333" in (published_item.external_post_id or "")


def test_meta_dual_facebook_succeeds_instagram_fails() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        url = str(request.url)
        if url == "https://graph.facebook.com/v21.0/page-123/photos":
            return httpx.Response(200, json={"post_id": "page-123_444"})
        if url == "https://graph.facebook.com/v21.0/ig-456/media":
            return httpx.Response(500, json={"error": {"message": "Temporary outage", "code": 2}})
        raise AssertionError(f"Unexpected request: {url}")

    sheets_service = FakeSheetsService(queue_item(platform="Meta Dual"))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    failed_item = result.failed_items[0]
    assert failed_item.status == "Partially Published"
    assert failed_item.published == "Partial"
    assert "Facebook=page-123_444" in (failed_item.external_post_id or "")
    assert "Instagram" in (failed_item.last_publish_error or "")


def test_meta_dual_duplicate_prevention_skips_existing_facebook_id() -> None:
    requests: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(str(request.url))
        if str(request.url) == "https://graph.facebook.com/v21.0/ig-456/media":
            return httpx.Response(200, json={"id": "creation-555"})
        if str(request.url) == "https://graph.facebook.com/v21.0/ig-456/media_publish":
            return httpx.Response(200, json={"id": "ig-media-555"})
        return httpx.Response(200, json={"id": "ig-media-555", "permalink": "https://instagram.com/p/555"})

    sheets_service = FakeSheetsService(queue_item(platform="Meta Dual", external_post_id="Facebook=page-123_555"))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert all("/page-123/" not in url for url in requests)
    assert "Facebook=page-123_555" in (result.published_items[0].external_post_id or "")
    assert "Instagram=ig-media-555" in (result.published_items[0].external_post_id or "")


def test_meta_auth_error_sets_publish_blocked() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(403, json={"error": {"message": "Missing permission", "code": 200}})

    sheets_service = FakeSheetsService(queue_item(platform="Facebook Page"))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert result.failed_items[0].status == "Publish Blocked"
    assert "Missing permission" in (result.failed_items[0].last_publish_error or "")


def test_meta_transient_error_sets_publish_failed() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(500, json={"error": {"message": "Temporary outage", "code": 2}})

    sheets_service = FakeSheetsService(queue_item(platform="Facebook Page"))
    publisher_service = PublisherService(
        app_settings=meta_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert result.failed_items[0].status == "Publish Failed"
    assert "Temporary outage" in (result.failed_items[0].last_publish_error or "")


def test_meta_export_generates_business_suite_package_without_api_calls() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError("meta_export must not call Meta APIs.")

    sheets_service = FakeSheetsService(
        queue_item(platform="Meta Dual", image_path="/media/campaigns/room.jpg", scheduled_at="2026-04-30T09:00:00Z")
    )
    publisher_service = PublisherService(
        app_settings=meta_export_settings(),
        meta_http_client_factory=lambda: http_client_factory(httpx.MockTransport(handler)),
    )
    result = PublishingWorkflowService(sheets_service, publisher_service).run_due_publishing()

    assert result.published_items == []
    exported_item = result.failed_items[0]
    assert exported_item.status == "Ready for Meta Business Suite"
    assert exported_item.published == "No"
    assert exported_item.publish_attempts == 1
    assert exported_item.last_publish_error is None
    assert "Meta Business Suite Package" in exported_item.notes
    assert "Facebook caption:" in exported_item.notes
    assert "Instagram caption:" in exported_item.notes
    assert "Image URL/Path: https://api.example.com/media/campaigns/room.jpg" in exported_item.notes
    assert "CTA: Request a quote" in exported_item.notes
    assert "Landing Page: https://gomezpainting.example/quote" in exported_item.notes
    assert "Suggested Schedule Time: 2026-04-30T09:00:00Z" in exported_item.notes
