import pytest
from httpx import ASGITransport, AsyncClient

from app.api.dependencies import get_publisher_service, get_sheets_service
from app.config import Settings
from app.main import app
from app.models.campaign_content import CampaignContentPublishResponse, CampaignContentQueueItem
from app.services.publisher_service import PublisherService


@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"


class FakeCampaignContentQueueSheetsService:
    def __init__(self, status: str = "Needs Review", approved: str = "No") -> None:
        self.item = CampaignContentQueueItem(
            content_id="CCQ-1001-facebook",
            campaign_id="CAMP-1001",
            platform="Facebook",
            draft_text="Facebook campaign draft",
            cta="Request a quote",
            landing_page_url="https://gomezpainting.example/quote",
            status=status,
            approved=approved,
            published="No",
            created_at="2026-04-28T00:00:00Z",
            published_at=None,
            notes="Generated by CampaignAgent",
        )
        self.updated_item: CampaignContentQueueItem | None = None

    def list_campaign_content_queue_items(self) -> list[CampaignContentQueueItem]:
        return [
            self.item,
            self.item.model_copy(
                update={
                    "content_id": "CCQ-1001-nextdoor",
                    "platform": "Nextdoor",
                    "draft_text": "Nextdoor draft",
                }
            ),
        ]

    def get_campaign_content_queue_item_by_id(self, content_id: str) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None
        return self.item

    def approve_campaign_content_queue_item(self, content_id: str) -> CampaignContentQueueItem | None:
        return self._update(content_id=content_id, status="Approved", approved="Yes", published="No")

    def reject_campaign_content_queue_item(self, content_id: str) -> CampaignContentQueueItem | None:
        return self._update(content_id=content_id, status="Rejected", approved="No", published="No")

    def mark_campaign_content_queue_item_published(self, content_id: str) -> CampaignContentQueueItem | None:
        return self._update(
            content_id=content_id,
            status="Published",
            approved="Yes",
            published="Yes",
            published_at="2026-04-28T01:00:00Z",
        )

    def publish_campaign_content_queue_item(
        self,
        content_id: str,
        published_at: str,
        notes: str,
        external_post_id: str | None = None,
        published_url: str | None = None,
    ) -> CampaignContentQueueItem | None:
        return self._update(
            content_id=content_id,
            status="Published",
            approved="Yes",
            published="Yes",
            published_at=published_at,
            notes=notes,
            external_post_id=external_post_id,
            published_url=published_url,
        )

    def schedule_campaign_content_queue_item(
        self,
        content_id: str,
        scheduled_at: str,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None

        self.updated_item = self.item.model_copy(
            update={
                "scheduled_at": scheduled_at,
                "published": "No",
            }
        )
        return self.updated_item

    def _update(
        self,
        content_id: str,
        status: str,
        approved: str,
        published: str,
        published_at: str | None = None,
        notes: str | None = None,
        external_post_id: str | None = None,
        published_url: str | None = None,
    ) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None

        update_payload = {
            "status": status,
            "approved": approved,
            "published": published,
            "published_at": published_at,
        }
        if notes is not None:
            update_payload["notes"] = notes
        if external_post_id is not None:
            update_payload["external_post_id"] = external_post_id
        if published_url is not None:
            update_payload["published_url"] = published_url

        self.updated_item = self.item.model_copy(update=update_payload)
        return self.updated_item


@pytest.mark.anyio
async def test_list_campaign_content_queue_items_returns_queue_items() -> None:
    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return FakeCampaignContentQueueSheetsService()

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get("/campaign-content-queue")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    data = response.json()
    assert len(data) == 2
    assert [item["content_id"] for item in data] == ["CCQ-1001-facebook", "CCQ-1001-nextdoor"]
    assert [CampaignContentQueueItem.model_validate(item).platform for item in data] == ["Facebook", "Nextdoor"]


@pytest.mark.anyio
async def test_approve_campaign_content_queue_item_returns_updated_item() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService()

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-1001-facebook/approve")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentQueueItem.model_validate(response.json())
    assert parsed_response.status == "Approved"
    assert parsed_response.approved == "Yes"
    assert parsed_response.published == "No"
    assert parsed_response.published_at is None
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_reject_campaign_content_queue_item_returns_updated_item() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService()

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-1001-facebook/reject")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentQueueItem.model_validate(response.json())
    assert parsed_response.status == "Rejected"
    assert parsed_response.approved == "No"
    assert parsed_response.published == "No"
    assert parsed_response.published_at is None
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_mark_campaign_content_queue_item_published_returns_updated_item() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService()

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-1001-facebook/mark-published")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentQueueItem.model_validate(response.json())
    assert parsed_response.status == "Published"
    assert parsed_response.approved == "Yes"
    assert parsed_response.published == "Yes"
    assert parsed_response.published_at == "2026-04-28T01:00:00Z"
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_campaign_content_queue_update_returns_404_when_content_id_is_missing() -> None:
    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return FakeCampaignContentQueueSheetsService()

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-missing/approve")

    app.dependency_overrides.clear()

    assert response.status_code == 404
    assert response.json() == {"detail": "Campaign content queue item not found for content_id: CCQ-missing"}


@pytest.mark.anyio
async def test_publish_campaign_content_queue_item_publishes_approved_item_in_mock_mode() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService(status="Approved", approved="Yes")
    publisher_service = PublisherService(app_settings=Settings(publisher_mode="mock"))

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    async def override_publisher_service() -> PublisherService:
        return publisher_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    app.dependency_overrides[get_publisher_service] = override_publisher_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-1001-facebook/publish")

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentPublishResponse.model_validate(response.json())
    assert parsed_response.publish_result.external_post_id == "mock-facebook-CCQ-1001-facebook"
    assert parsed_response.publish_result.published_url.endswith("/mock-facebook-CCQ-1001-facebook")
    assert parsed_response.queue_item.status == "Published"
    assert parsed_response.queue_item.approved == "Yes"
    assert parsed_response.queue_item.published == "Yes"
    assert parsed_response.queue_item.published_at is not None
    assert parsed_response.queue_item.external_post_id == "mock-facebook-CCQ-1001-facebook"
    assert parsed_response.queue_item.published_url is not None
    assert "external_post_id=mock-facebook-CCQ-1001-facebook" in parsed_response.queue_item.notes
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_publish_campaign_content_queue_item_rejects_needs_review_item() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService(status="Needs Review", approved="No")

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-1001-facebook/publish")

    app.dependency_overrides.clear()

    assert response.status_code == 409
    assert response.json() == {"detail": "Campaign content must be approved before publishing."}
    assert fake_sheets_service.updated_item is None


@pytest.mark.anyio
async def test_publish_campaign_content_queue_item_rejects_rejected_item() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService(status="Rejected", approved="No")

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-1001-facebook/publish")

    app.dependency_overrides.clear()

    assert response.status_code == 409
    assert response.json() == {"detail": "Campaign content must be approved before publishing."}
    assert fake_sheets_service.updated_item is None


@pytest.mark.anyio
async def test_publish_campaign_content_queue_item_returns_404_when_content_id_is_missing() -> None:
    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return FakeCampaignContentQueueSheetsService(status="Approved", approved="Yes")

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/campaign-content-queue/CCQ-missing/publish")

    app.dependency_overrides.clear()

    assert response.status_code == 404
    assert response.json() == {"detail": "Campaign content queue item not found for content_id: CCQ-missing"}


@pytest.mark.anyio
async def test_schedule_campaign_content_queue_item_schedules_approved_item() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService(status="Approved", approved="Yes")

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post(
            "/campaign-content-queue/CCQ-1001-facebook/schedule",
            json={"scheduled_at": "2026-04-30T09:00:00Z"},
        )

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentQueueItem.model_validate(response.json())
    assert parsed_response.scheduled_at == "2026-04-30T09:00:00Z"
    assert parsed_response.published == "No"
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_schedule_campaign_content_queue_item_rejects_needs_review_item() -> None:
    fake_sheets_service = FakeCampaignContentQueueSheetsService(status="Needs Review", approved="No")

    async def override_sheets_service() -> FakeCampaignContentQueueSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post(
            "/campaign-content-queue/CCQ-1001-facebook/schedule",
            json={"scheduled_at": "2026-04-30T09:00:00Z"},
        )

    app.dependency_overrides.clear()

    assert response.status_code == 409
    assert response.json() == {"detail": "Campaign content must be approved before scheduling."}
    assert fake_sheets_service.updated_item is None
