import pytest
from httpx import ASGITransport, AsyncClient

from app.api.dependencies import get_sheets_service
from app.main import app
from app.models.campaign_content import CampaignContentQueueItem


@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"


class FakePostsSheetsService:
    def __init__(self) -> None:
        self.item = CampaignContentQueueItem(
            content_id="WSQ-1001-meta-dual-1",
            campaign_id="CAMP-1001",
            platform="Meta Dual",
            draft_text="Original draft",
            cta="Request a quote",
            landing_page_url="https://marompainting.org",
            status="Draft",
            approved="No",
            published="No",
            created_at="2026-04-29T12:00:00Z",
            scheduled_at="2026-04-29T12:00:00Z",
            notes="Generated by Weekly Social Queue\nBusiness: Marom Painting\nWeek: 2026-W18",
        )
        self.updated_item: CampaignContentQueueItem | None = None

    def update_post_draft_text(self, content_id: str, draft_text: str) -> CampaignContentQueueItem | None:
        if content_id != self.item.content_id:
            return None
        self.updated_item = self.item.model_copy(update={"draft_text": draft_text})
        return self.updated_item


@pytest.mark.anyio
async def test_update_post_draft_text_returns_updated_post() -> None:
    fake_sheets_service = FakePostsSheetsService()

    async def override_sheets_service() -> FakePostsSheetsService:
        return fake_sheets_service

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.patch(
            "/posts/WSQ-1001-meta-dual-1/draft-text",
            json={"draft_text": "Edited draft text"},
        )

    app.dependency_overrides.clear()

    assert response.status_code == 200
    parsed_response = CampaignContentQueueItem.model_validate(response.json())
    assert parsed_response.draft_text == "Edited draft text"
    assert fake_sheets_service.updated_item is not None


@pytest.mark.anyio
async def test_update_post_draft_text_returns_404_when_post_is_missing() -> None:
    async def override_sheets_service() -> FakePostsSheetsService:
        return FakePostsSheetsService()

    app.dependency_overrides[get_sheets_service] = override_sheets_service
    transport = ASGITransport(app=app)

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.patch(
            "/posts/WSQ-missing/draft-text",
            json={"draft_text": "Edited draft text"},
        )

    app.dependency_overrides.clear()

    assert response.status_code == 404
    assert response.json() == {"detail": "Post not found for content_id: WSQ-missing"}
